### ISSUE TITLE
 Discussion on fit_ellipse.ipynb

### ISSUE THREAD

**Issue by glyg** [hadim/public_notebooks#1]
Hi @hadim 

Nice notebook. This method is efficient, and I didn't spot obvious errors.

Some remarks:
- Is the `where(a==1)` necessary? I get that it's easier to compute the moment down the road, but only applies to a binary image. Evaluating $x\,y\,I(x, y)$ directly would be more general.
- When you compute the eigenvalues from the computation of $\Delta$, it would be nice to point that it comes from the roots of the 2nd order equation $\det(cov - I) = 0$ or explicitly 
  $(\mu_{20} - 1)(\mu_{02} - 1) - \mu_{11}^2 = 0$. 
- Have you looked at opencv `fit_ellipse` and the equivalent from scikit-image?
- I think the underestimate comes from the fact that you have a binary image, and an implicit hypothesis on why the length of the axes scales with the covariance matrix eigenvalues is that the function $f(x, y)$ is a 2D Gaussian (from a normal distribution), and the computed width the full width at $1/e^2$ or something like that.
- Knowing the above, what's the result with the grayscale image? What if you use a fake 2D Gaussian  image?

**Comment by hadim** [comment]
I will investigate all of that. Thanks !
